name: database
description: Local database layer using Isar.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.7
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.9

