name: chemical_reference
description: Database of common lab chemicals and solubility data.
version: 0.0.1
environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  assets:
    - assets/chemicals.json
