name: experiment_log
description: Voice-First Experiment Logging feature.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.7
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  intl: any
  speech_to_text: ^7.3.0
  permission_handler: ^11.3.0
  csv: ^6.0.0
  share_plus: ^10.1.4
  path_provider: ^2.1.2
  cross_file: ^0.3.4
  image_picker: ^1.0.7


  
  # Local Packages
  ui_kit:
    path: ../ui_kit
  database:
    path: ../../core/database
  math_engine:
    path: ../../core/math_engine

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.9
